services:
  - type: web
    name: midni
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install numpy==1.24.3
      pip install torch==2.1.2 torchaudio==2.1.2 --index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn tts_saas.wsgi:application --log-file - --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: ai-voice-clone-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: noreply@midni.com
      - key: BASE_URL
        value: https://midni.onrender.com
      - key: KORAPAY_SECRET_KEY
        sync: false
      - key: KORAPAY_PUBLIC_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 1

databases:
  - name: ai-voice-clone-db
    databaseName: aivoiceclone
    plan: free
