# Generated by Django 5.2.4 on 2026-03-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_generationhistory_voice_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='paystack_customer_code',
            new_name='korapay_customer_code',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='paystack_subscription_code',
            new_name='korapay_subscription_code',
        ),
    ]
